version: '3'
services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET:=duc_secret_k3y
      - NODE_ENV=development
      - PORT=5003
    depends_on:
      - db
    volumes:
      - .:/app


  db:
    image: "postgres:13-alpine"
    container-name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data