### GET / 
GET http://localhost:5004/

### POST /auth/register

POST http://localhost:5004/auth/register
Content-Type: application/json

{
    "username": "test",
    "password": "12321"
}
### POST auth/login
POST http://localhost:5004/auth/login
Content-Type: application/json

{
    "username": "test",
    "password": "12321"
}
### 